"""Schema version constants for DRYML environment metadata."""

ENVIRONMENT_RECORD_SCHEMA_VERSION = "1.1"
ENVIRONMENT_REQUIREMENT_SCHEMA_VERSION = "1.1"
ENVIRONMENT_SPEC_SCHEMA_VERSION = "1.1"
ENVIRONMENT_LOCK_REF_SCHEMA_VERSION = "1.1"
COMPATIBILITY_REPORT_SCHEMA_VERSION = 1
ENVIRONMENT_PROBE_RESULT_SCHEMA_VERSION = 1

__all__ = [
    "ENVIRONMENT_RECORD_SCHEMA_VERSION",
    "ENVIRONMENT_REQUIREMENT_SCHEMA_VERSION",
    "ENVIRONMENT_SPEC_SCHEMA_VERSION",
    "ENVIRONMENT_LOCK_REF_SCHEMA_VERSION",
    "COMPATIBILITY_REPORT_SCHEMA_VERSION",
    "ENVIRONMENT_PROBE_RESULT_SCHEMA_VERSION",
]
