"""Public authoring and logical-reference API for managed operations."""

from .declarations import (
    DelegatedOutputs,
    ManagedMethodDeclaration,
    ManagedOutput,
    ManagedOutputs,
    OutputDeclaration,
    OutputDeclarations,
    normalize_outputs,
    resolve_definition_path,
)
from .descriptor import BoundManagedMethod, ManagedMethod, managed
from .errors import (
    AmbiguousManagedStoreError,
    DuplicateOutputError,
    InvalidSubjectPathError,
    ManagedDeclarationError,
    ManagedError,
    ManagedInputValidationRequiredError,
    ManagedLeaseConflictError,
    ManagedLifecycleUnavailableError,
    ManagedRerunRequiredError,
    ManagedStateError,
    ManagedStoreUnsupportedError,
    ManagedTakeoverRequiredError,
    PrimaryOutputError,
    StaleManagedLeaseError,
    StaleManagedResultError,
    UnknownOutputError,
    UnstableOutputsError,
)
from .refs import ManagedOutputRef
from .state import (
    ActivationEvent,
    GenerationControl,
    NamespaceState,
    OperationDecision,
    OperationKey,
    RealizationState,
    declaration_fingerprint,
)
from .store import (
    ManagedOperationStore,
    OperationControl,
    OperationLease,
    resolve_managed_store,
)

__all__ = [
    "ActivationEvent",
    "AmbiguousManagedStoreError",
    "BoundManagedMethod",
    "DelegatedOutputs",
    "DuplicateOutputError",
    "GenerationControl",
    "InvalidSubjectPathError",
    "ManagedDeclarationError",
    "ManagedError",
    "ManagedInputValidationRequiredError",
    "ManagedLeaseConflictError",
    "ManagedLifecycleUnavailableError",
    "ManagedMethod",
    "ManagedMethodDeclaration",
    "ManagedOperationStore",
    "ManagedOutput",
    "ManagedOutputRef",
    "ManagedOutputs",
    "ManagedRerunRequiredError",
    "ManagedStateError",
    "ManagedStoreUnsupportedError",
    "ManagedTakeoverRequiredError",
    "NamespaceState",
    "OperationControl",
    "OperationDecision",
    "OperationKey",
    "OperationLease",
    "OutputDeclaration",
    "OutputDeclarations",
    "PrimaryOutputError",
    "RealizationState",
    "StaleManagedLeaseError",
    "StaleManagedResultError",
    "UnknownOutputError",
    "UnstableOutputsError",
    "declaration_fingerprint",
    "managed",
    "normalize_outputs",
    "resolve_definition_path",
    "resolve_managed_store",
]
