"""Public authoring and logical-reference API for managed operations."""

from .declarations import (
    DelegatedOutputs,
    ManagedMethodDeclaration,
    ManagedOutput,
    ManagedOutputs,
    OutputDeclaration,
    OutputDeclarations,
    normalize_outputs,
    resolve_definition_path,
)
from .descriptor import BoundManagedMethod, ManagedMethod, managed
from .callbacks import (
    CallbackCoordinator,
    ControlRequest,
    ManagedCallback,
    normalize_callbacks,
    preflight_callbacks,
)
from .context import (
    OperationContext,
    OperationPreflight,
    OperationResult,
    OutputEffect,
    current_operation_context,
)
from .events import EventBuffer, OperationEvent, ProgressSnapshot
from .errors import (
    AmbiguousManagedStoreError,
    CallbackFailure,
    ConcurrentManagedActivationError,
    DuplicateOutputError,
    InvalidSubjectPathError,
    ManagedDeclarationError,
    ManagedCapabilityError,
    ManagedCleanupRefusedError,
    ManagedError,
    ManagedInputValidationRequiredError,
    ManagedLeaseConflictError,
    ManagedInterruptedError,
    ManagedLifecycleUnavailableError,
    ManagedRerunRequiredError,
    ManagedOutputError,
    ManagedStateError,
    ManagedStoreUnsupportedError,
    ManagedTakeoverRequiredError,
    MissingManagedOutputError,
    PrimaryOutputError,
    StaleManagedLeaseError,
    StaleManagedResultError,
    UnknownOutputError,
    UnstableOutputsError,
)
from .cleanup import (
    CleanupPlan,
    CleanupReport,
    execute_cleanup,
    plan_cleanup,
    resume_cleanup,
)
from .export import (
    RecipeExportReport,
    RealizationTransferReport,
    export_recipe,
    transfer_realizations,
)
from .refs import ManagedOutputRef
from .resolution import resolve_inputs, resolve_output
from .runtime import ManagedInvocationResult, ManagedStatus
from .state import (
    ActivationEvent,
    GenerationControl,
    NamespaceState,
    OperationDecision,
    OperationKey,
    RealizationState,
    declaration_fingerprint,
)
from .store import (
    ManagedOperationStore,
    OperationControl,
    OperationLease,
    resolve_managed_store,
)

__all__ = [
    "ActivationEvent",
    "AmbiguousManagedStoreError",
    "BoundManagedMethod",
    "CallbackCoordinator",
    "CallbackFailure",
    "ConcurrentManagedActivationError",
    "ControlRequest",
    "CleanupPlan",
    "CleanupReport",
    "DelegatedOutputs",
    "DuplicateOutputError",
    "EventBuffer",
    "GenerationControl",
    "InvalidSubjectPathError",
    "ManagedDeclarationError",
    "ManagedCapabilityError",
    "ManagedCleanupRefusedError",
    "ManagedError",
    "ManagedInputValidationRequiredError",
    "ManagedInterruptedError",
    "ManagedInvocationResult",
    "ManagedLeaseConflictError",
    "ManagedLifecycleUnavailableError",
    "ManagedMethod",
    "ManagedMethodDeclaration",
    "ManagedOperationStore",
    "ManagedOutputError",
    "ManagedOutput",
    "ManagedOutputRef",
    "ManagedOutputs",
    "ManagedRerunRequiredError",
    "ManagedStatus",
    "ManagedStateError",
    "ManagedStoreUnsupportedError",
    "ManagedTakeoverRequiredError",
    "ManagedCallback",
    "MissingManagedOutputError",
    "NamespaceState",
    "OperationControl",
    "OperationContext",
    "OperationDecision",
    "OperationEvent",
    "OperationKey",
    "OperationLease",
    "OperationPreflight",
    "OperationResult",
    "OutputEffect",
    "OutputDeclaration",
    "OutputDeclarations",
    "PrimaryOutputError",
    "ProgressSnapshot",
    "RecipeExportReport",
    "RealizationState",
    "RealizationTransferReport",
    "StaleManagedLeaseError",
    "StaleManagedResultError",
    "UnknownOutputError",
    "UnstableOutputsError",
    "declaration_fingerprint",
    "current_operation_context",
    "execute_cleanup",
    "export_recipe",
    "managed",
    "normalize_outputs",
    "normalize_callbacks",
    "preflight_callbacks",
    "plan_cleanup",
    "resolve_inputs",
    "resolve_output",
    "resume_cleanup",
    "resolve_definition_path",
    "resolve_managed_store",
    "transfer_realizations",
]
