"""Lazy public facade for core definitions, persistence, and query APIs."""

from __future__ import annotations

import importlib
import sys
from types import ModuleType


_EXPORT_MODULES = {
    "Object": "dryml.core.object",
    "Serializable": "dryml.core.object",
    "UniqueID": "dryml.core.object",
    "Metadata": "dryml.core.object",
    "Compute": "dryml.core.object",
    "definition_mode": "dryml.core.object",
    "selector_mode": "dryml.core.object",
    "space_mode": "dryml.core.object",
    "ConcreteDefinition": "dryml.core.definition",
    "Definition": "dryml.core.definition",
    "SKIP_ARGS": "dryml.core.definition",
    "freeze": "dryml.core.definition",
    "DefLink": "dryml.core.links",
    "AutoRef": "dryml.core.signatures",
    "Mat": "dryml.core.signatures",
    "Ref": "dryml.core.signatures",
    "SignatureError": "dryml.core.signatures",
    "function": "dryml.core.signatures",
    "normalize_args": "dryml.core.signatures",
    "normalize_return": "dryml.core.signatures",
    "signature_context": "dryml.core.signatures",
    "ObjectId": "dryml.core.reference_values",
    "ObjectRef": "dryml.core.reference_values",
    "StateRef": "dryml.core.reference_values",
    "StateSelectorRef": "dryml.core.reference_values",
    "object_namespace": "dryml.core.reference_values",
    "AnyValue": "dryml.core.params",
    "Choice": "dryml.core.params",
    "Exact": "dryml.core.params",
    "IntRange": "dryml.core.params",
    "Missing": "dryml.core.params",
    "Par": "dryml.core.params",
    "Present": "dryml.core.params",
    "Satisfies": "dryml.core.params",
    "SubclassOf": "dryml.core.params",
    "UniformFromSet": "dryml.core.params",
    "UniformIntRange": "dryml.core.params",
    "QuotedDef": "dryml.core.quoted",
    "SelectorSpec": "dryml.core.quoted",
    "SearchSpace": "dryml.core.search_space",
    "Selector": "dryml.core.selector",
    "selector": "dryml.core.selector",
    "Repo": "dryml.core.repo",
    "RepoDefinition": "dryml.core.repo_definition",
    "RepoDefinitionError": "dryml.core.repo_definition",
    "RepoReconstructionError": "dryml.core.repo_definition",
    "load_object": "dryml.core.repo",
    "load_state_ref": "dryml.core.repo",
    "save_object": "dryml.core.repo",
    "LiveReusePolicy": "dryml.core.policies",
    "StoreReport": "dryml.core.repo_plan",
    "SavePublication": "dryml.core.repo_plan",
    "SavedSnapshot": "dryml.core.repo_plan",
    "PublicationPhase": "dryml.core.repo_plan",
    "PublicationStatus": "dryml.core.repo_plan",
    "SaveRouting": "dryml.core.repo_plan",
    "StateGraphReservation": "dryml.core.state",
    "dtype": "dryml.core.dtype",
    "DType": "dryml.core.dtype",
    "SpecHint": "dryml.core.tensor_spec",
    "TensorSpec": "dryml.core.tensor_spec",
    "as_tensor_spec": "dryml.core.tensor_spec",
    "CONFIG_MISSING": "dryml.core.config",
    "ConfigError": "dryml.core.config",
    "ConfigRef": "dryml.core.config",
    "FactorySpec": "dryml.core.factory",
    "configure": "dryml.core.session",
    "reset_config": "dryml.core.session",
    "status": "dryml.core.session",
    "ImportRef": "dryml.core.symbol",
    "SourceSpec": "dryml.core.symbol",
    "resolve_symbol": "dryml.core.symbol",
    "symbol_ref": "dryml.core.symbol",
    "CDefEdge": "dryml.core.cdef_graph",
    "CDefNode": "dryml.core.cdef_graph",
    "CDefOccurrence": "dryml.core.cdef_graph",
    "ConcreteDefinitionGraph": "dryml.core.cdef_graph",
    "ConcreteDefinitionGraphCycleError": "dryml.core.cdef_graph",
    "ConcreteDefinitionGraphError": "dryml.core.cdef_graph",
    "EdgeKind": "dryml.core.cdef_graph",
    "iter_direct_cdef_edges": "dryml.core.cdef_graph",
    "Arg": "dryml.core.query",
    "DefinitionPath": "dryml.core.query",
    "DefinitionQuery": "dryml.core.query",
    "DefinitionResultSet": "dryml.core.query",
    "GraphPathError": "dryml.core.query",
    "Index": "dryml.core.query",
    "Key": "dryml.core.query",
    "Kwarg": "dryml.core.query",
    "Parameter": "dryml.core.query",
    "ObjectResultSet": "dryml.core.query",
    "ObjectRefResultSet": "dryml.core.query",
    "OccurrenceResultSet": "dryml.core.query",
    "ReferenceOccurrence": "dryml.core.query",
    "ReferenceQuery": "dryml.core.query",
    "ReferenceResultSet": "dryml.core.query",
    "QueryCardinalityError": "dryml.core.query",
    "QueryDomainError": "dryml.core.query",
    "QueryError": "dryml.core.query",
    "QueryExplanation": "dryml.core.query",
    "QueryIndexError": "dryml.core.query",
    "QueryPathError": "dryml.core.query",
    "SetMember": "dryml.core.query",
    "StateRefResultSet": "dryml.core.query",
    "CoreExecutionError": "dryml.core.execute",
    "CoreExecutionFuture": "dryml.core.execute",
    "CoreExecutionSnapshot": "dryml.core.execute",
    "CoreOptions": "dryml.core.execute",
    "CoreOutcomeEvidence": "dryml.core.execute",
    "CorePublicationEvidence": "dryml.core.execute",
    "CoreRefreshEvidence": "dryml.core.execute",
    "Executor": "dryml.core.execute",
    "ExecutorView": "dryml.core.execute",
    "PreparedCoreCall": "dryml.core.execute",
    "SharedDirStoreStrategy": "dryml.core.execute",
    "run": "dryml.core.execute",
    "submit": "dryml.core.execute",
    "SaveAnnotations": "dryml.core.metadata",
    "LineageMetadata": "dryml.core.metadata",
    "SnapshotCapture": "dryml.core.metadata",
    "SnapshotMetadata": "dryml.core.metadata",
    "encode_metadata_mapping": "dryml.core.metadata",
    "decode_metadata_mapping": "dryml.core.metadata",
    "timestamp_to_seconds": "dryml.core.metadata",
    "timestamp_from_seconds": "dryml.core.metadata",
    "encode_current_annotations": "dryml.core.metadata",
    "decode_current_annotations": "dryml.core.metadata",
    "encode_lineage_metadata": "dryml.core.metadata",
    "decode_lineage_metadata": "dryml.core.metadata",
    "encode_snapshot_metadata": "dryml.core.metadata",
    "decode_snapshot_metadata": "dryml.core.metadata",
    "read_snapshot_metadata": "dryml.core.metadata",
    "MetadataScalar": "dryml.core.metadata",
    "MetadataValue": "dryml.core.metadata",
    "MetadataMapping": "dryml.core.metadata",
    "MetadataTarget": "dryml.core.metadata",
    "MetadataDiagnostic": "dryml.core.metadata",
    "EnvironmentStatus": "dryml.core.metadata",
    "RequirementStatus": "dryml.core.metadata",
    "EvidenceCoverage": "dryml.core.metadata",
}


def __getattr__(name: str) -> object:
    """Return one documented core export, loading and caching it on first access.

    Args:
        name: Public export name listed in :data:`__all__`.

    Returns:
        The identically owned object from its defining core module.

    Raises:
        AttributeError: If ``name`` is not a documented core export.

    Side Effects:
        Imports the export's owner module and stores the resolved object in this
        module's namespace.
    """

    try:
        module_name = _EXPORT_MODULES[name]
    except KeyError:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from None
    value = getattr(importlib.import_module(module_name), name)
    globals()[name] = value
    return value

__all__ = [
    "load_object",
    "save_object",
    "load_state_ref",
    "LiveReusePolicy",
    "StoreReport",
    "SavePublication",
    "SavedSnapshot",
    "PublicationPhase",
    "PublicationStatus",
    "SaveRouting",
    "StateGraphReservation",
    "Object",
    "Serializable",
    "UniqueID",
    "Metadata",
    "Compute",
    "Definition",
    "ConcreteDefinition",
    "DefLink",
    "Ref",
    "Mat",
    "AutoRef",
    "normalize_args",
    "normalize_return",
    "signature_context",
    "function",
    "SignatureError",
    "ObjectId",
    "ObjectRef",
    "StateRef",
    "StateSelectorRef",
    "object_namespace",
    "freeze",
    "QuotedDef",
    "SelectorSpec",
    "Selector",
    "selector",
    "Par",
    "Present",
    "Missing",
    "AnyValue",
    "Exact",
    "Choice",
    "IntRange",
    "SubclassOf",
    "Satisfies",
    "UniformIntRange",
    "UniformFromSet",
    "SearchSpace",
    "SKIP_ARGS",
    "Repo",
    "RepoDefinition",
    "RepoDefinitionError",
    "RepoReconstructionError",
    "configure",
    "reset_config",
    "status",
    "definition_mode",
    "selector_mode",
    "space_mode",
    "dtype",
    "DType",
    "ConfigRef",
    "FactorySpec",
    "ConfigError",
    "CONFIG_MISSING",
    "as_tensor_spec",
    "SpecHint",
    "TensorSpec",
    "ImportRef",
    "SourceSpec",
    "symbol_ref",
    "resolve_symbol",
    "CDefEdge",
    "CDefNode",
    "CDefOccurrence",
    "ConcreteDefinitionGraph",
    "ConcreteDefinitionGraphCycleError",
    "ConcreteDefinitionGraphError",
    "EdgeKind",
    "iter_direct_cdef_edges",
    "Arg",
    "DefinitionPath",
    "DefinitionQuery",
    "DefinitionResultSet",
    "GraphPathError",
    "Index",
    "Key",
    "Kwarg",
    "Parameter",
    "ObjectResultSet",
    "ObjectRefResultSet",
    "OccurrenceResultSet",
    "ReferenceOccurrence",
    "ReferenceQuery",
    "ReferenceResultSet",
    "QueryCardinalityError",
    "QueryDomainError",
    "QueryError",
    "QueryExplanation",
    "QueryIndexError",
    "QueryPathError",
    "SetMember",
    "StateRefResultSet",
    "CoreExecutionError",
    "CoreExecutionFuture",
    "CoreExecutionSnapshot",
    "CoreOptions",
    "CoreOutcomeEvidence",
    "CorePublicationEvidence",
    "CoreRefreshEvidence",
    "Executor",
    "ExecutorView",
    "PreparedCoreCall",
    "SharedDirStoreStrategy",
    "run",
    "submit",
    "SaveAnnotations",
    "LineageMetadata",
    "SnapshotCapture",
    "SnapshotMetadata",
    "encode_metadata_mapping",
    "decode_metadata_mapping",
    "timestamp_to_seconds",
    "timestamp_from_seconds",
    "encode_current_annotations",
    "decode_current_annotations",
    "encode_lineage_metadata",
    "decode_lineage_metadata",
    "encode_snapshot_metadata",
    "decode_snapshot_metadata",
    "read_snapshot_metadata",
    "MetadataScalar",
    "MetadataValue",
    "MetadataMapping",
    "MetadataTarget",
    "MetadataDiagnostic",
    "EnvironmentStatus",
    "RequirementStatus",
    "EvidenceCoverage",
]


class _CoreModule(ModuleType):
    """Protect public names that collide with importable core submodules."""

    def __getattribute__(self, name: str) -> object:
        if name in _EXPORT_MODULES:
            value = vars(self).get(name)
            if value is None or isinstance(value, ModuleType):
                return __getattr__(name)
        return super().__getattribute__(name)


sys.modules[__name__].__class__ = _CoreModule
