"""Dependency-light record/spec sidecar APIs for DRYML stores."""

from .errors import (
    RecordClosureError,
    RecordError,
    RecordExportError,
    RecordIOError,
    RecordNotFoundError,
    RecordPolicyError,
    RecordValidationError,
    SpecNotFoundError,
    SpecValidationError,
    StorageRefError,
)
from .records import (
    RECORD_ID_PREFIX,
    RECORD_SCHEMA,
    RECORD_SCHEMA_VERSION,
    attach_record_id,
    compute_record_id,
    make_record,
    record_payload_for_id,
    validate_record,
)
from .refs import LocatedRecordRef, LocatedSpecRef, RecordRef, SpecRef
from .adapters import (
    AdapterDescriptor,
    AdapterExecutionContext,
    AdapterExecutionResult,
    AdapterPlan,
    AdapterRegistry,
    AdapterStep,
    adapter_descriptors_from_report,
    find_adapter_path,
    run_adapter_plan,
)
from .scanner import ReferenceMention, scan_json_refs, scan_record_refs, scan_spec_refs, scan_store_refs
from .index import (
    RECORD_REF_INDEX_FILENAME,
    RECORD_REF_INDEX_SCHEMA,
    RECORD_REF_INDEX_SCHEMA_VERSION,
    RecordRefIndex,
    RecordRefIndexDirty,
    RecordRefIndexError,
    RecordRefIndexMissing,
    RecordRefIndexRebuildReport,
    RecordRefIndexValidationError,
    build_record_ref_index,
    validate_record_ref_index,
)
from .export import RecordClosurePlan, copy_record_closure, plan_record_closure, record_export_include_paths
from .federation import RepoRecordFederation
from .policy import (
    DEFAULT_RECORD_POLICY,
    RECORD_POLICIES,
    RECORD_POLICY_ALL,
    RECORD_POLICY_CLOSURE,
    RECORD_POLICY_DESCRIPTIVE,
    RECORD_POLICY_NONE,
    RECORD_POLICY_PROVENANCE,
    RecordPolicyOptions,
    RecordPolicyReport,
    apply_save_record_policy,
    default_object_state_representation_spec,
    normalize_record_policy,
    policy_includes_products,
    stored_state_record_for_save_action,
)
from .specs import (
    SPEC_FAMILIES,
    attach_spec_id,
    compute_spec_id,
    make_spec,
    spec_dir_name,
    spec_family_for_id,
    spec_id_prefix,
    spec_payload_for_id,
    validate_spec,
)
from .products import (
    ProductManifest,
    ProductManifestEntry,
    ProductWriteResult,
    ProductWriteSession,
    commit_product_record,
    stage_product_file,
)
from .representations import (
    RepresentationCompatibilityReport,
    RepresentationRequirement,
    RepresentationSpec,
    make_representation_spec,
    representation_satisfies,
    validate_representation_spec,
)
from .resolution import (
    LocatedTypedRecord,
    RecordResolutionIssue,
    RecordResolutionReport,
    RepresentationCandidate,
    StateResolutionRequest,
    StateResolutionResult,
    find_compatible_state_record,
    find_stored_state_records,
    resolve_state_record,
)
from .storage import StorageRef
from .store import RecordStoreIO
from .typed import AdapterRecord, DataRecord, ProgramRecord, StoredStateRecord, typed_record_from_envelope


__all__ = [
    "DEFAULT_RECORD_POLICY",
    "RECORD_ID_PREFIX",
    "RECORD_POLICIES",
    "RECORD_POLICY_ALL",
    "RECORD_POLICY_CLOSURE",
    "RECORD_POLICY_DESCRIPTIVE",
    "RECORD_POLICY_NONE",
    "RECORD_POLICY_PROVENANCE",
    "RECORD_SCHEMA",
    "RECORD_SCHEMA_VERSION",
    "SPEC_FAMILIES",
    "LocatedRecordRef",
    "LocatedSpecRef",
    "LocatedTypedRecord",
    "AdapterDescriptor",
    "AdapterExecutionContext",
    "AdapterExecutionResult",
    "AdapterPlan",
    "AdapterRecord",
    "AdapterRegistry",
    "AdapterStep",
    "DataRecord",
    "ProductManifest",
    "ProductManifestEntry",
    "ProductWriteResult",
    "ProductWriteSession",
    "ProgramRecord",
    "RecordClosureError",
    "RecordClosurePlan",
    "RecordError",
    "RecordExportError",
    "RecordIOError",
    "RECORD_REF_INDEX_FILENAME",
    "RECORD_REF_INDEX_SCHEMA",
    "RECORD_REF_INDEX_SCHEMA_VERSION",
    "RecordRefIndex",
    "RecordRefIndexDirty",
    "RecordRefIndexError",
    "RecordRefIndexMissing",
    "RecordRefIndexRebuildReport",
    "RecordRefIndexValidationError",
    "RecordNotFoundError",
    "RecordPolicyError",
    "RecordPolicyOptions",
    "RecordPolicyReport",
    "RecordRef",
    "RecordResolutionIssue",
    "RecordResolutionReport",
    "RepoRecordFederation",
    "RecordStoreIO",
    "RecordValidationError",
    "ReferenceMention",
    "RepresentationCandidate",
    "RepresentationCompatibilityReport",
    "RepresentationRequirement",
    "RepresentationSpec",
    "SpecNotFoundError",
    "SpecRef",
    "SpecValidationError",
    "StateResolutionRequest",
    "StateResolutionResult",
    "StorageRef",
    "StorageRefError",
    "StoredStateRecord",
    "adapter_descriptors_from_report",
    "attach_record_id",
    "attach_spec_id",
    "apply_save_record_policy",
    "build_record_ref_index",
    "compute_record_id",
    "compute_spec_id",
    "commit_product_record",
    "copy_record_closure",
    "default_object_state_representation_spec",
    "find_adapter_path",
    "find_compatible_state_record",
    "find_stored_state_records",
    "make_record",
    "make_representation_spec",
    "make_spec",
    "normalize_record_policy",
    "plan_record_closure",
    "policy_includes_products",
    "representation_satisfies",
    "resolve_state_record",
    "record_payload_for_id",
    "record_export_include_paths",
    "run_adapter_plan",
    "scan_json_refs",
    "scan_record_refs",
    "scan_spec_refs",
    "scan_store_refs",
    "spec_dir_name",
    "spec_family_for_id",
    "spec_id_prefix",
    "spec_payload_for_id",
    "stored_state_record_for_save_action",
    "stage_product_file",
    "typed_record_from_envelope",
    "validate_record",
    "validate_record_ref_index",
    "validate_representation_spec",
    "validate_spec",
]
