"""Dependency-light record/spec sidecar APIs for DRYML stores."""

from .errors import (
    RecordClosureError,
    RecordError,
    RecordExportError,
    RecordIOError,
    RecordNotFoundError,
    RecordPolicyError,
    RecordValidationError,
    SpecNotFoundError,
    SpecValidationError,
    StorageRefError,
)
from .records import (
    RECORD_ID_PREFIX,
    RECORD_SCHEMA,
    RECORD_SCHEMA_VERSION,
    attach_record_id,
    compute_record_id,
    make_record,
    record_payload_for_id,
    validate_record,
)
from .refs import LocatedRecordRef, LocatedSpecRef, RecordRef, SpecRef
from .scanner import ReferenceMention, scan_json_refs, scan_record_refs, scan_spec_refs, scan_store_refs
from .index import (
    RECORD_REF_INDEX_FILENAME,
    RECORD_REF_INDEX_SCHEMA,
    RECORD_REF_INDEX_SCHEMA_VERSION,
    RecordRefIndex,
    RecordRefIndexDirty,
    RecordRefIndexError,
    RecordRefIndexMissing,
    RecordRefIndexRebuildReport,
    RecordRefIndexValidationError,
    build_record_ref_index,
    validate_record_ref_index,
)
from .export import RecordClosurePlan, copy_record_closure, plan_record_closure, record_export_include_paths
from .federation import RepoRecordFederation
from .policy import (
    DEFAULT_RECORD_POLICY,
    RECORD_POLICIES,
    RECORD_POLICY_ALL,
    RECORD_POLICY_CLOSURE,
    RECORD_POLICY_DESCRIPTIVE,
    RECORD_POLICY_NONE,
    RECORD_POLICY_PROVENANCE,
    RecordPolicyOptions,
    RecordPolicyReport,
    apply_save_record_policy,
    default_object_state_representation_spec,
    normalize_record_policy,
    policy_includes_products,
    stored_state_record_for_save_action,
)
from .specs import (
    SPEC_FAMILIES,
    attach_spec_id,
    compute_spec_id,
    make_spec,
    spec_dir_name,
    spec_family_for_id,
    spec_id_prefix,
    spec_payload_for_id,
    validate_spec,
)
from .storage import StorageRef
from .store import RecordStoreIO


__all__ = [
    "DEFAULT_RECORD_POLICY",
    "RECORD_ID_PREFIX",
    "RECORD_POLICIES",
    "RECORD_POLICY_ALL",
    "RECORD_POLICY_CLOSURE",
    "RECORD_POLICY_DESCRIPTIVE",
    "RECORD_POLICY_NONE",
    "RECORD_POLICY_PROVENANCE",
    "RECORD_SCHEMA",
    "RECORD_SCHEMA_VERSION",
    "SPEC_FAMILIES",
    "LocatedRecordRef",
    "LocatedSpecRef",
    "RecordClosureError",
    "RecordClosurePlan",
    "RecordError",
    "RecordExportError",
    "RecordIOError",
    "RECORD_REF_INDEX_FILENAME",
    "RECORD_REF_INDEX_SCHEMA",
    "RECORD_REF_INDEX_SCHEMA_VERSION",
    "RecordRefIndex",
    "RecordRefIndexDirty",
    "RecordRefIndexError",
    "RecordRefIndexMissing",
    "RecordRefIndexRebuildReport",
    "RecordRefIndexValidationError",
    "RecordNotFoundError",
    "RecordPolicyError",
    "RecordPolicyOptions",
    "RecordPolicyReport",
    "RecordRef",
    "RepoRecordFederation",
    "RecordStoreIO",
    "RecordValidationError",
    "ReferenceMention",
    "SpecNotFoundError",
    "SpecRef",
    "SpecValidationError",
    "StorageRef",
    "StorageRefError",
    "attach_record_id",
    "attach_spec_id",
    "apply_save_record_policy",
    "build_record_ref_index",
    "compute_record_id",
    "compute_spec_id",
    "copy_record_closure",
    "default_object_state_representation_spec",
    "make_record",
    "make_spec",
    "normalize_record_policy",
    "plan_record_closure",
    "policy_includes_products",
    "record_payload_for_id",
    "record_export_include_paths",
    "scan_json_refs",
    "scan_record_refs",
    "scan_spec_refs",
    "scan_store_refs",
    "spec_dir_name",
    "spec_family_for_id",
    "spec_id_prefix",
    "spec_payload_for_id",
    "stored_state_record_for_save_action",
    "validate_record",
    "validate_record_ref_index",
    "validate_spec",
]
